[tool.poetry]
name = "vita"
version = "0.1.0"
description = ""
authors = ["applyuser160 <syunsuke130121@gamil.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pre-commit = "^4.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
