name: Run Tests on Push or PR

on:
  push:
    branches: [ master, develop, 'feature/*' ]
  pull_request:
    branches: [ master, develop, 'feature/*' ]

jobs:
  test:
    defaults:
      run:
        working-directory: vita

    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Make poetry environment
        run: |
          pip install poetry
          poetry install

      - name: Run tests
        run: poetry run pytest
